version: '3'

services: 
    deploy-docker-django:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes: 
            - ./deploy-docker-django:/deploy-docker-django
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DEBUG=1