version: '3'

services: 
    deploy-docker-django:
        build:
            context: .
        volumes:
            - static_data:/vol/web
        environment:
            - SECRET_KEY=samplesecretkeY123
            - ALLOWED_HOSTS=127.0.0.1,localhost
    proxy:
        build:
            context: ./proxy
        volumes: 
            - static_data:/vol/web
        ports:
            - "8080:8080"
        depends_on: 
            - deploy-docker-django

volumes: 
    static_data:
